<?php

namespace tests;

use components\Config;

class ConfigTest extends \PHPUnit\Framework\TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetConfigArray()
    {
        $testConfigExpected = ["testKey" => "testValue"];
        $producedConfig = Config::getConfigArray("../tests/_data/config_test");

        self::assertEquals($testConfigExpected, $producedConfig);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}