<?php

class RouterTest extends \PHPUnit\Framework\TestCase
{
    public \http\Router $router;
    public function setUp(): void
    {
//        $_SERVER["REQUEST_URI"] = "/";
    }

    public function testExecuteActionIndex()
    {
        $_SERVER["REQUEST_URI"] = "/";
        $router = new \http\Router();
        $router->executeAction();

        self::assertEquals(<<<HEREDOC

        <h1>Welcome to DANCEOFTHEKNIGHTS</h1>
        <h3>To start subscribing to goods, follow <a href="/olx/subscribe">the link</a></h3>

        HEREDOC, ob_get_clean());
    }

    public function testExecuteActionNonExistent()
    {
        $_SERVER["REQUEST_URI"] = "/rrr/";
        $router = new \http\Router();
        $router->executeAction();

        self::assertEquals("404", ob_get_clean());
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}